project:
  type: website
  output-dir: docs
website:
  title: "Simon's Public NAO Notebook"
  navbar:
    background: "#5cb2a0"
    foreground: white
    search: true
    left:
     - text: Dashboard
       href: dashboard/index.qmd
format:
  html:
    css: styles.css
toc: true
number-sections: false
