{
  "hash": "6ecd19ec5a68881c9ef28b4348e37923",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Modeling routine swab sampling of asymptomatic individuals\nsubtitle: Sequencing swabs in non-hospital settings could offer cheap and sensitive pathogen early detection\nauthor: Simon Grimm\ndate: '2024-04-06'\nformat:\n  docx:\n    toc: true\n    echo: false\neditor: visual\ntoc: true\nfilters:\n  - black-formatter\n---\n\n\n\n\nThe NAO aims to detect stealth pathogens at an early stage. Initially we mostly thought about detecting pathogens in wastewater, but we've recently expanded our research to also cover [air sampling](https://naobservatory.org/reports/air-sampling-for-early-pathogen-detection), created a more general framework with which to think about the promise of different [sampling strategies](https://naobservatory.org/reports/comparing-sampling-strategies-for-early-detection-of-stealth-biothreats), and built a simulator that is agnostic to the [underlying sampling method](https://naobservatory.org/blog/simulating-approaches-to-metagenomic-pandemic-identification).\n\nOne sample type we've been thinking about more recently is swab sampling. Jeff Kaufman recently wrote a piece that provides an initial estimate of the [sensitivity of swab sampling](https://www.jefftk.com/p/sequencing-swabs). The post here expands on this initial piece of work by using our more relative abundance advanced simulator on a larger set of swab sampling studies. Additionally we create a BOTEC estimate for what relative abundances could look like in the kind of sampling program we envision (collect anterior nasal swabs (heretofore called nasal swabs) from a random sample of people at an airport terminal or some other public location).\n\nIn summary, ....\n\n### Lu et al. 2021\n\nJeff originally wrote a post that is based on Lu et al. 2021, which sampled Chinese patients with oropharyngeal swabs (throat, or OP swabs). The paper gives little information on patient characteristics. COVID-19 abundance in Lu et al. 2021 is fairly high with a mean relative abudance of 2x10<sup>-3</sup> (n=16).\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![**Figure 1: qPCR CT values and relative abundance for Lu et al. 2021.**](index_files/figure-docx/cell-4-output-1.png){}\n:::\n:::\n\n\nWe can use this data to estimate the expected cumulative incidence upon detection. Let's say we get a random set of swabs on each weekday, pooling and sequencing them using a Nanopore MinION which produces 800,000 reads. We need two suspicious reads for detection (where there is only one genetic site within the pathogen that is suspicious). If we vary the number of swabs, ranging from 50 to 800, median cumulative incidence is expected to be 2% when sampling 50 swabs, 1.2% when sampling 100 swabs, 0.6 % at 200 swabs, 0.4% at 400 swabs, and 0.2% at 800 swabs. That's pretty good!\n\n::: {.cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![**Figure 2: Simulated cumulative incidence at time of detection for Lu et al. 2021.**\n Assuming swab sample sizes ranging from 50-800.](index_files/figure-docx/cell-5-output-1.png){}\n:::\n:::\n\n\nLet's take a closer look at the median outcome. If we run the simulation for each swab sample size between 50 and 800, pick the median cumulative incidence and plot the medians only we get the following curve. This still looks quite good: when we  use more than 200 swabs we reliably get a cumulative incidence that is below 1%. But what happens if we use a different study as our \"ground truth\" for the expected relative abundance in swabs?\n\n::: {.cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![**Figure 3: Simulated cumulative incidence at time of detection for Lu et al. 2021.**\n Median outcome for sample sizes between 1 and 800 swabs.](index_files/figure-docx/cell-6-output-1.png){}\n:::\n:::\n\n\n### Additional SARS-CoV-2 studies\n\nLu et al. 2021 is a relatively small sample of inpatients in Wuhan but there are other studies that have done similar work. Limiting ourselves to COVID-19, there is Babiker et al. 2020, which sampled poth inpatients and outpatients using nasopharyngeal swabs, Mostafa et al. 2020, which sampled nasal swabs from patients which range from being outpatients to individuals that required a ventilator and Rodriguez et al. 2021, which sampled nasopharyngeal swabs from inpatients and outpatients. We call these studies \"target studies\" heretoforth. The average relative SARS-CoV-2 relative abundance for Babiker et al. 2020 is 2x10<sup>-4</sup> (n=44), 10<sup>-4</sup> for Mostafa et al. 2020 (n=33), and 1.2x10<sup>-3</sup>. This compares to a relative abudance of 2x10<sup>-3</sup> (n=16) in  Lu et al. 2021 (Fig 4).\n\n::: {.cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![**Figure 4: SARS-CoV-2 qPCR CT vs SARS-CoV-2 RA.**\nFirst Figure: Throat Swabs. Data from Lu et al. 2021. Second Figure: NP Swabs. Data from Babiker et al. 2020. Third Figure: Nasal Swabs. Data from Mostafa et al. 2020. Fourth Figure: Nasal Swabs. Data from Rodriguez et al. 2021.](index_files/figure-docx/cell-7-output-1.png){}\n:::\n:::\n\n\n\nLet's recreate Figure 3 for these new studies. Again, we assume a swab sampling program that sampled 50-800 swabs a day. If we take the relative abundance values of these three studies as the relative abundance we'd expect to see in a swab sampling program Lu et al. 2021 shows a cumulative incidence of 0.6% (200 swabs) and 0.3 % (400 swabs), Babiker et al. 2020 shows 1.2% and 0.9%, Mostafa et al. 2020 1.7% and 1.4% and Rodriguez et al. 0.7% and 0.3% respectively.\n\n::: {.cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![**Figure 5: Simulated RA(1%) for Lu et al. 2021, Babiker et al. 2020, Mostafa et al. 2020, and Rodriguez et al. 2021.**\n Assuming swab sample sizes between 50 and 800.](index_files/figure-docx/cell-9-output-1.png){}\n:::\n:::\n\n\n## What would a more representative sample look like?\n\nThe studies we've looked at all have issues that keep them from being representative of the sort of population sampling we're considering. There are four different aspects we can look at:\n\n1. Most patients were hospitalized, but in a hypothetical sampling program individuals would either be asymptomatic or only slightly sick (otherwise they would stay home)\n2. Likely close to all patients were symptomatic, but the kind of stealth pathogen we are looking for would be expected to show no symptoms.\n3. Studies either used nasopharyngeal swabs ( Babiker et al. 2020, Mostafa et al. 2020, and Rodriguez et al. 2021), or oropharyngeal swabs (Lu et al. 2021) but a sampling program would most likely use anterior nasal swabs.\n4. Finally, many of the inpatients covered by our four target studies were sampled later in their disease course, but viral loads are highest just when symptoms begin. But when sampling asymptomatic individuals the time between testing and initial infection would likely be random and sampling could thus occur more closely to the start of symptoms when compared to inpatients.\n\nLet's see if we can get an intuition for the magnitude for these effects.\n\n\n### Swab type\n\n#### Nasopharyngeal vs Nasal swabs\n\nBoth Babiker et al. 2020, Mostafa et al. 2020, and Rodriguez et al. 2021 used nasopharyngeal swabs. We found five studies that performed paired sampling and SARS-CoV-2 qPCR of the same patients: Patriquin et al. 2022, McCulloch et al. 2020, Pere et al 2020, Kojima et al. 2020, and Tu et al. 2020. For each of these studies we have individual data points for each sample pair. By computing the CT difference within each pair, and averaging these differences we get an average CT difference for each study (Table S1, Fig.6). Averaging these values again without weighing studies we get an average difference of **-1.82** CT values, where negative values mean that nasopharyngeal swabs have lower CT values and are thus more sensitive.\n\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![**Figure 6: Nasal swabs vs nasopharyngeal swabs.** Data from Patriquin et al. 2022, McCulloch et al. 2020, Pere et al. 2020, Kojima et al. 2020, and Tu et al. 2020.](index_files/figure-docx/np_nasal_ct_plot-output-1.png){#np_nasal_ct_plot}\n:::\n:::\n\n\n##### Oropharyngeal vs Nasal swabs\n\nLu et al. 2021 uses oropharyngeal swabs. We can adjust this swab type by looking at the studies , Leungt et al. 2022, Goodall et al. 2022 and Berenger et al. 2020. We have raw data for Goodall et al. 2022, Leung et al. 2020, and median CT values for Berenger et al. 2022. Averaging the qPCR results for qPCR target N and ORF1a for each sample, Goodall et al. 2022 showed an average CT value difference (OP-Nasal) of **1** Ct value in favor of nasal swabs. In Berenger et al. 2022 the difference between medians (OP - NP) was 1.1 (E gene) and 0.8 (RdRp). This gives an across-study average difference of 1 CT value, maing OP swabs less sensitive than nasal swabs.\n\n::: {.cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![**Figure 7: Nasal swabs vs Oro-pharyngeal swabs.** Data is taken from Goodall et al. 2022 and Leung et al 2020.](index_files/figure-docx/cell-12-output-1.png){}\n:::\n:::\n\n\n### Inpatient vs Outpatient\n\n::: {.cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![**Figure 8: Patient composition of Lu et al. 2021, Babiker et al. 2020, Mostafa et al. 2020, and Rodriguez et al. 2021.**](index_files/figure-docx/target-studies-patient-composition-output-1.png){#target-studies-patient-composition}\n:::\n:::\n\n\nWe can adjust for this somewhat by looking at the average difference of the CT values for inpatients and outpatients (Table 1). It's worth noting that inpatients typically have **higher** CT values, which is unexpected, given that they are likely to be sicker.\n\n| Study | Sample size | Sample type| Inpatient CT (median, IQR) | Outpatient CT (median, IQR) | CT value difference (Inpatient - Outpatient)|\n|-------|-------------|------------|----------------------------|-------------------------------|-----|\n| [Souverein et al. 2022](https://academic.oup.com/ofid/article/9/7/ofac223/6576478#:~:text=26.3%20(IQR%2C%205.7).-,Association%20Between%20Cp%20Value%20and%20Hospital%20Admission,-Of%20the%2020)  | 19897 outpatients, 310 inpatients | OP/NP  |26.3 (5.6) | 25.0 (5.2) | 1.3 |\n| [Knudtzen et al. 2021](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258421#:~:text=SARS%2DCoV%2D2%20PCR%20Cq%2Dvalue%20as%20a%20marker%20for%20hospital%20admission) | 87 outpatients, 82 inpatients | 13 OP/NP, 130 OP, 26 sputum | 26.9 (7.7) | 24.6 (6.7)| 2.3|\n| [Babiker et al. 2020](https://journals.asm.org/doi/10.1128/jcm.02142-20) | 10 outpatients, 34 inpatients | NP | 24.25 (7.8) | 25.35 (5.8) | -1.1|\n| [Rodriguez et al. 2021](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1009416#sec010) | 42 outpatients, 17 inpatients | NP | 30.0 (7.0) | 24.0 (6.8) | 6 |\n: Table 1: Studies that sampled both inpatients and outpatients (includes two of our target studies)\n\n### Disease onset\n\nThe lower viral load in inpatients is most likely caused by them entering the hospital later. Indeed, as we see in Knudtzen et al. 2021 which ran a prospective cohort study on a inpatient and outpatient cohort, the inpatient samples were collected later.\n\n\n\n![Figure from [Knudtzen et al. 2021](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258421): Relationship between days since symptom onset and viral load.](img/knudtzen-et-al-2021.png)\n\n\nTwo other studies also provide data on viral load in relation to disease onset: Bullard et al. 2020 and He et al. 2020.\n\n| Study Name| No. of patients | Swab type| Patient type |\n|-----------|-----------------|----------|--------------|\n| [Knudtzen et al. 2021](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258421) | 169 | NP and/or OP, Saliva | 87 outpatients, 82 stationary |\n| [Bullard et al. 2020](https://academic.oup.com/cid/article/71/10/2663/5842165) | 90 | NP or endotracheal (ETT) | Samples at a public health lab |\n| [He et al. 2020](https://www.nature.com/articles/s41591-020-0869-5) | 94 | throat | inpatients (none were severe or critically ill) |\n: Table 2: Studies that provide information on viral load in relation to disease onset.\n\nLooking at this data there is a fairly clear relationship between time and lower viral load. (Need to account for the outlier in Knudtzen et al. inpatients where a couple of patients that were tested very late showed lot CT values)\n\n::: {.cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![**Figure 9: qPCR CT Value vs Days since symptom onset** Data is taken from Knudtzen et al. 2021, Bullard et al. 2020, and He et al. 2020.](index_files/figure-docx/cell-14-output-1.png){}\n:::\n:::\n\n\n### Asymptomatic individuals\n\nFinally, a further difference between our target studies and the ultimate sampling program we are considering is that sampled individuals would be asymptomatic. We identified four studies that researched this questions. Information on these papers can be found in Appendix 2.\n\n| Study | Sample size | Sample type | Symptomatic CT Value (median, IQR) | Asymptomatic CT Value (median, IQR) |\n|----------------------|----------------------------|----------------------|-------------------------------|-------------------------------|\n| [Hall et al. 2022](https://doi.org/10.1371/journal.pone.0270694) | 357 asymptomatic, 1276 symptomatic or pre-symptomatic | Anterior nasal swab | N1: 21.8 (17.2-29.4), N2: 21.4 (17.3-28.9) | N1: 29.9 (23.6-35.5), N2: 30.0 (23.1-35.7) |\n| [Long et al. 2020](https://doi.org/10.1038/s41591-020-0965-6) | 37 asymptomatic, 37 symptomatic | NP | ORF1ab: 31.7 (30.3-35.1), N: 33.5 (31.3-37.2) | ORF1ab: 32.8 (30.9-35.8), N: 32.6 (29.5-34.6) |\n| [Lee et al. 2022](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2769235) | 89 asymptomatic, 214 symptomatic | NP, OP, sputum | no raw data | no raw data |\n| [Zhou et al. 2020](https://doi.org/10.1016/j.ijid.2020.05.030) | 9 asymptomatic, 22 pre-symptomatic | NP | 34.5 (32.2-37.0) | 39.0 (37.5-39.5) |\n: Table 2: Viral load in symptomatic and asymptomatic individuals. Lee et al 2022 provides no raw data but noted that there was no significant difference between symptomatic and asympatomic individuals.\n\n### A BOTEC for the sensitivity pooled swab sampling program\n\nWe can use the factors above to adjust the data in our target datasets. Note that this very much has the status of a BOTEC and would require more sophisticated modelling for us to put much faith in it. Anyway, let's for now:\n\n1. Drop all samples that are from ICU or ventilator patients.\n2. Adjust nasopharyngeal and oropharyngeal swabs by the adjustment factors discussed earlier (+1.82 for NP, -1 for OP samples)\n3. Adjust inpatient samples by the observed difference to outpatient samples (-2.1) #TODISCUSS, this is clearly wrong.\n4. Adjust all samples to resemble asymptomatics (+4.3)\n5. #TODO Adjust for days.\n\n::: {.cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![**Figure 10: Data extrapolated to asymptomatic individuals, sampled with anterior nasal swabs**](index_files/figure-docx/cell-15-output-1.png){}\n:::\n:::\n\n\nHow does this compare to our initial estimate regarding sensitivity? We get worse sensitivity, but nothing that's too bad. At 200 swabs, the composite dataset gives us a cumulative incidence of 1%, and at 400 swabs one of 0.7%. This compares to 0.5, and 0.3% for Lu et al. 2021.\n\n::: {.cell execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![**Figure 11: Simulated RA(1%) for Lu et al. 2021, and our extrapolated dataset**\n Assuming swab sample sizes between 50 and 800.](index_files/figure-docx/cell-16-output-1.png){}\n:::\n:::\n\n\n# Appendix\n\n##### Appendix 1: Adjusting for swab type\n\n| Study Name| No. of positive pairs | NP CT - Nasal CT| Collection method |\n|-----------|-----------------------|-------------------|-----------------|\n| [Patriquin et al. 2022](https://journals.asm.org/doi/full/10.1128/spectrum.02455-21) | 70 | -3| Both professionally collected|\n| [McCulloch et al. 2020](https://jamanetwork.com/journals/jamanetworkopen/article-abstract/2768535) | 21 | -1.6| Nasal was self-collected, NP was professionally collected |\n| [Pere et al 2020](https://journals.asm.org/doi/full/10.1128/jcm.00721-20) | 23 |-1|Both professionally collected|\n| [Kojima et al. 2020](https://academic.oup.com/cid/article/73/9/e3106/5930814?login=false) | 30  |-4|Nasal was self-collected, NP was professionally collected|\n| [Tu et al. 2020](https://www.nejm.org/doi/full/10.1056/NEJMc2016321) | 46 |0| Nasal was self-collected, NP was professionally collected|\n: Table S1: Nasal swabs vs nasopharyngeal swabs.\n\n| Study Name| No. of positive pairs | CT/Genome Copy Number difference[^2] | Collection method | Pathogen |\n|-----------|-----------------------|---------------------------------------|-------------------|----------|\n| [Berenger et al. 2020](https://www.medrxiv.org/content/10.1101/2020.05.05.20084889v1.full) | 19 | 1 | Both professionally collected| SARS-CoV-2 |\n| [Goodall et al. 2022](https://journals.asm.org/doi/10.1128/spectrum.00217-22#core-B16) | 58 | 0.95 | Both self-collected | SARS-CoV-2 |\n| [Leung et al. 2022](https://www.nature.com/articles/s41591-020-0843-2)| 11, 33, 37 | X, Y, Z | Both self-collected | HCoV, Influenza, Rhinovirus |\n: Table S2: Oropharyngeal swabs vs nasal swabs.\n\n\n[^2]: qPCr differences are computed by subtracting the CT value of OP swab mean with the one of Nasal swabs. Genome copy number differences are computed by subtracting the genome copy number log of OP swabs from the genome copy number log of Nasal swabs.\n##### Appendix 2: Adjusting for days since symptom onset\n\n\n| Study Name| No. of patients | Swab type| Patient type |\n|-----------|-----------------|----------|--------------|\n| [Knudtzen et al. 2021](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258421) | 169 | NP and/or OP, Saliva | 87 outpatients, 82 stationary |\n| [Bullard et al. 2020](https://academic.oup.com/cid/article/71/10/2663/5842165) | 90 | NP or endotracheal (ETT) | Samples at a public health lab |\n| [He et al. 2020](https://www.nature.com/articles/s41591-020-0869-5) | 94 | throat | inpatients (none were severe or critically ill) |\n: Table S3: Days since symptom onset.\n\nThe data from these different studies is not available, but we can extract it from the relevant figures:\n\n:::{.column-page layout-ncol=3}\n\n![He et al. 2020](img/he-et-al-2020.png)\n\n![Bullard et al. 2020](img/bullard-et-al-2020.png)\n\n![Knudtzen et al. 2021](img/knudtzen-et-al-2021.png)\n\nFigure X: Relationship between days since symptom onset and viral load.\n:::\n\n::: {.cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-docx/cell-17-output-1.png){}\n:::\n:::\n\n\n##### Appendix 3: Inpatients vs Outpatients\n\nThere are two studies that have done this and looked at the average qPCR cycle threshold (CT) values in swabs of inpatients and outpatients. Souverein et al. 2022 looked at a dataset of 20207 positive COVID-19 tests that were all performed at two public health testing facilities in the Netherlands. Patients were subsequently classified as inpatients or outpatients if they got admitted to a hospital within 30 days of their initial test. The results from this study are thus somewhat imperfect: They do not measure the CT value of current in-/outpatients but rather show the CT value difference between patients who went on to be hospitalized or not. Still, based on this data the CT value difference between individuals who remained outpatients and individuals who went on to become inpatients was -1.3 (25.0-26.3), where inpatients had lower viral loads (and thus a higher CT value). Knudtzen et al. 2021 more closely resembles what we are looking for. Here, researchers identified the qPCR CT values of outpatients (n=87) through an outpatient cohort study and the values of hospitalized patients (n=82) through medical records. The CT value difference was -2.3 (24.6 - 26.9) again in favor of outpatients. Again there some limitations to study because researchers used [three different qPCR assays](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258421#:~:text=SARS%2DCoV%2D2%20detection%20was%20established%20on%20three%20different%20analysis%20platforms%E2%80%94the%20fully%20automated%20high%20throughput%20Cobas%206800%20(Roche)%2C%20the%20commercially%20available%20kit%20RealStar%C2%AE%20SARS%2DCoV%2D2%20RT%2DPCR%20kit%201.0%20(Altona%20Diagnostics)%20and%20a%20laboratory%20developed%20real%2Dtime%20(RT)%2DPCR.), and there is no data on patient/qPCR matches. Finally, two of the MGS studies also included both inpatients and outpatients at meaningful numbers (Babiker at al. 2020, Rodriguez et al. 2021). Babiker et al. 2020 included 10 outpatients and  34 inpatients. All nasopharyngeal swab samples were analyzed with qPCR by the researchers themselves, presumably using the same protocol for all samples. Looking at this data we find that CT values in inpatients are 1.15 points lower (25.35-24.25). For Rodriguez et al. 2021, both outpatients (n=42) and inpatients (n=17) were tested with the same qPCR assay (RealStar SARS-CoV-2 RT-PCR Kit, Altona Diagnostics, Hamburg, Germany). Here the average CT value in inpatients was 6 CTs higher  in outpatients (24-30).\n\nWithout weighing the studies the inpatients have an average qPCR result that is **~2.1** CT values higher.\n\n| Study                | Sample size                | Sample type          | Inpatient CT (median, IQR)           | Outpatient CT (median, IQR)                |\n|----------------------|----------------------------|----------------------|-------------------------------|-------------------------------|\n| [Souverein et al. 2022](https://academic.oup.com/ofid/article/9/7/ofac223/6576478#:~:text=26.3%20(IQR%2C%205.7).-,Association%20Between%20Cp%20Value%20and%20Hospital%20Admission,-Of%20the%2020)  | 19897 outpatients, 310 inpatients | OP/NP  |     26.3 (5.6)                   | 25.0 (5.2) |\n| [Knudtzen et al. 2021](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0258421#:~:text=SARS%2DCoV%2D2%20PCR%20Cq%2Dvalue%20as%20a%20marker%20for%20hospital%20admission) | 87 outpatients, 82 inpatients | 13 OP/NP, 130 OP, 26 sputum | 26.9 (7.7) | 24.6 (6.7)|\n| [Babiker et al. 2020](https://journals.asm.org/doi/10.1128/jcm.02142-20) | 10 outpatients, 34 inpatients | NP | 24.25 (7.8) | 25.35 (5.8) |\n| [Rodriguez et al. 2021](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1009416#sec010) | 42 outpatients, 17 inpatients | NP | 30.0 (7.0) | 24.0 (6.8) |\n: Table S4: Inpatient vs Outpatient data.\n\n\n##### Appendix 4: Adjusting for asymptomatic individuals\n\nOnce we've adusted for the inpatient population we still need to account for individuals being symptomatic. To make this symptomatic to asymptomatic adjustement, we found four different studies. Hall et al. 2022 looked at the results of a university testing program that tracked symptoms upon taking the test and thereafter. The median CT of asymptomatic individuals was around 8 points higher, with symptomatic patients showing a CT value of 21.8 (N1) and 21.4 (N2) compared to 29.9 (N1) and 30.0 (N2) for asymptomatics. Long et al. 2020 compared 37 asymptomatic individuals to 37 symptomatic patients and found no clear difference in median CT values between the two groups, with the median symptomatic CT value for ORF1ab being 1 point lower and the median value for N being 0.9 higher compared to asymptmatics. Lee et al. 2021 studied patients in an isolation facility. They do not provide raw data or median values, but report there was no qPCR CT value difference between symptomatic and asymptomatic patients in their study. Let's treat this as zero for now (#FIXME). Finally, Zhou et al. 2020 investigated 31 patients who were asymptomatic on admission, of which 22 developed symptoms later (pre-symptomatic) and 9 remained asymptomatic. Here the median CT of symptomatics was 4.5 points lower.\n\nAgain, without weighing the studies the average CT value difference of symptomatic or pre-symptomatic is **~4.3** CT values lower than that of individuals who remain asymptomatic.\n\n| Study | Sample size | Sample type | Symptomatic CT Value (median, IQR) | Asymptomatic CT Value (median, IQR) |\n|----------------------|----------------------------|----------------------|-------------------------------|-------------------------------|\n| [Hall et al. 2022](https://doi.org/10.1371/journal.pone.0270694) | 357 asymptomatic, 1276 symptomatic or pre-symptomatic | Anterior nasal swab | N1: 21.8 (17.2-29.4), N2: 21.4 (17.3-28.9) | N1: 29.9 (23.6-35.5), N2: 30.0 (23.1-35.7) |\n| [Long et al. 2020](https://doi.org/10.1038/s41591-020-0965-6) | 37 asymptomatic, 37 symptomatic | NP | ORF1ab: 31.7 (30.3-35.1), N: 33.5 (31.3-37.2) | ORF1ab: 32.8 (30.9-35.8), N: 32.6 (29.5-34.6) |\n| [Lee et al. 2022](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2769235) | 89 asymptomatic, 214 symptomatic | NP, OP, sputum | no raw data | no raw data |\n| [Zhou et al. 2020](https://doi.org/10.1016/j.ijid.2020.05.030) | 9 asymptomatic, 22 pre-symptomatic | NP | 34.5 (32.2-37.0) | 39.0 (37.5-39.5) |\n: Table S5: Days since symptom onset.\n\n",
    "supporting": [
      "index_files/figure-docx"
    ],
    "filters": []
  }
}